# This is a basic workflow to help you get started with Actions

name: CI CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branches
  push:
    branches: [ dev-*, prod-* ]
  pull_request:
    branches: [ dev-*, prod-* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH: github.ref_name

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dev-build:
    name: Build and push dev image to Docker Hub
    if: startsWith( github.ref, 'refs/heads/dev-' )
    runs-on: ubuntu-latest
    steps:
    - name: Show branch name
      run: echo ${{ env.BRANCH }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops21-metodik2:${{ env.BRANCH }}-latest
